apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: srishtieee/api-gateway-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: INFERENCE_URL
              value: "http://inference-service:8000/predict"
            - name: DATABASE_URL
              value: "http://database-service:8002/store"
