apiVersion: apps/v1                            
kind: StatefulSet                              
metadata:
  name: postgres                            
spec:
  serviceName: postgres-headless           
  replicas: 1                                 
  selector:
    matchLabels:
      app: postgres                           
  template:
    metadata:
      labels:
        app: postgres                        
    spec:
      containers:
      - name: postgres                         
        image: postgres:16-alpine               # Official Postgres image
        ports:
        - containerPort: 5432                   
        envFrom: 
        - secretRef:
            name: db-secret                     
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes: 
      - name: init-sql
        configMap:
          name: db-init-sql                        # Mount SQL script from ConfigMap

  volumeClaimTemplates:                       
  - metadata:
      name: postgres-data                          # PVC name
    spec:
      accessModes: ["ReadWriteOnce"]           
      resources:
        requests:
          storage: 2Gi                             # Request 2GB storage