# Securely store and manage sensitive information 

apiVersion: v1              # Use v1 API version for Secret
kind: Secret                # Define kind as Secret
metadata:
  name: db-secret           # Name of Secret
type: Opaque                # Type of Secret, Opaque for key-value pairs
stringData:                 # Text Values 
  POSTGRES_DB: egtdb        # Database name 
  POSTGRES_USER: egtdb      # Database username
  POSTGRES_PASSWORD: egtdb  # Database password