apiVersion: v1            
kind: Secret              
metadata:
  name: db-secret          
type: Opaque                # Type of Secret, Opaque for key-value pairs
stringData:                 
  POSTGRES_DB: egtdb        
  POSTGRES_USER: egtdb      
  POSTGRES_PASSWORD: egtdb 